# Generated by Django 5.2.12 on 2026-03-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriber', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcriptjob',
            options={'ordering': ['-created_at']},
        ),
    ]
