# Generated by Django 5.2.12 on 2026-03-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriber', '0002_alter_transcriptjob_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptjob',
            name='normalized_audio_file',
            field=models.FileField(blank=True, null=True, upload_to='processed/audio/%Y/%m/%d/'),
        ),
    ]
