# Generated by Django 5.2.12 on 2026-03-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriber', '0003_transcriptjob_normalized_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptjob',
            name='selected_language',
            field=models.CharField(choices=[('auto', 'Auto detect'), ('en', 'English'), ('bg', 'Bulgarian')], default='auto', max_length=10),
        ),
    ]
