# Generated by Django 5.2.12 on 2026-03-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriber', '0004_transcriptjob_selected_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptjob',
            name='expected_speaker_count',
            field=models.CharField(choices=[('auto', 'Auto detect'), ('2', '2 speakers'), ('3', '3 speakers'), ('4', '4 speakers')], default='auto', max_length=10),
        ),
    ]
